---
title: "人工智能知識及應用證書（兼讀制）: 神經網路"
output: html_notebook
---



 

Task 1: load the required package
```{r}
library(package='neuralnet')
```


Task 2: load the yahoo data 
```{r}


trainData = read.csv(file='/Users/admin/prj/ERB_AI/Data/^HSI.csv', header=TRUE)

print(trainData)
```

task 3: Create an additional column to determine whether the closing value for today has increased or decreased compared to the Opening value for today.
```{r}


trainData$updown = ifelse(trainData$Open<trainData$Close, 1 , 0) 
print(trainData)
```



Task 4: Complete the model 
```{r}
model=neuralnet(formula       =  updown~Open+High+Low ,
                data          =  trainData            , 
                hidden        =  c(5,5)               ,
                stepmax       =  1e+05                , 
                act.fct       = "logistic"            ,
                linear.output = FALSE                 )
```




Task 5: Predict today's HSI
```{r}
predictData=neuralnet::compute(model, data.frame(Open=15894, High=15993.88, Low=15082.84))
print(predictData)
```




